/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.lang.Math;
/**
 *
 * @author zomsik
 */
public class Calculator extends javax.swing.JFrame {
    char calculation;
    double remembertocalculation;
    double remembertocalculation2=0;
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisplayScreen = new javax.swing.JLabel();
        XtoPowY = new javax.swing.JButton();
        Divide = new javax.swing.JButton();
        RemoveLastNumber = new javax.swing.JButton();
        SquareRoot = new javax.swing.JButton();
        Multiply = new javax.swing.JButton();
        Number9 = new javax.swing.JButton();
        Number8 = new javax.swing.JButton();
        Number7 = new javax.swing.JButton();
        Substract = new javax.swing.JButton();
        Number6 = new javax.swing.JButton();
        Number5 = new javax.swing.JButton();
        Number4 = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Number3 = new javax.swing.JButton();
        Number2 = new javax.swing.JButton();
        Number1 = new javax.swing.JButton();
        Equal = new javax.swing.JButton();
        Numberdot = new javax.swing.JButton();
        Number0 = new javax.swing.JButton();
        ResetCalculator = new javax.swing.JButton();
        CalculationScreen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        DisplayScreen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DisplayScreen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DisplayScreen.setText("0");

        XtoPowY.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        XtoPowY.setText("x^y");
        XtoPowY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XtoPowYActionPerformed(evt);
            }
        });

        Divide.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Divide.setText("÷");
        Divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivideActionPerformed(evt);
            }
        });

        RemoveLastNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RemoveLastNumber.setText("CE");
        RemoveLastNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveLastNumberActionPerformed(evt);
            }
        });

        SquareRoot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SquareRoot.setText("√");
        SquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquareRootActionPerformed(evt);
            }
        });

        Multiply.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Multiply.setText("x");
        Multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplyActionPerformed(evt);
            }
        });

        Number9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Number9.setText("9");
        Number9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number9ActionPerformed(evt);
            }
        });

        Number8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Number8.setText("8");
        Number8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number8ActionPerformed(evt);
            }
        });

        Number7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Number7.setText("7");
        Number7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number7ActionPerformed(evt);
            }
        });

        Substract.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Substract.setText("-");
        Substract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubstractActionPerformed(evt);
            }
        });

        Number6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Number6.setText("6");
        Number6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number6ActionPerformed(evt);
            }
        });

        Number5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Number5.setText("5");
        Number5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number5ActionPerformed(evt);
            }
        });

        Number4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Number4.setText("4");
        Number4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number4ActionPerformed(evt);
            }
        });

        Add.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Add.setText("+");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Number3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Number3.setText("3");
        Number3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number3ActionPerformed(evt);
            }
        });

        Number2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Number2.setText("2");
        Number2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number2ActionPerformed(evt);
            }
        });

        Number1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Number1.setText("1");
        Number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number1ActionPerformed(evt);
            }
        });

        Equal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Equal.setText("=");
        Equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqualActionPerformed(evt);
            }
        });

        Numberdot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Numberdot.setText(".");
        Numberdot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberdotActionPerformed(evt);
            }
        });

        Number0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Number0.setText("0");
        Number0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number0ActionPerformed(evt);
            }
        });

        ResetCalculator.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ResetCalculator.setText("C");
        ResetCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetCalculatorActionPerformed(evt);
            }
        });

        CalculationScreen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CalculationScreen.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Number7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Number8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Number9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Number4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Number5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Number6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Substract, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Number1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Number2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Number3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Number0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Numberdot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Equal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RemoveLastNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(ResetCalculator, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(XtoPowY, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Divide, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(DisplayScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CalculationScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(CalculationScreen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DisplayScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ResetCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RemoveLastNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(XtoPowY, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Divide, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Number9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Number7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Number8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Number6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Substract, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Number4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Number5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Number3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Number1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Number2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Equal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Number0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Numberdot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void ClearCalculator()
    {
        String Display = "0";
        CalculationScreen.setText(" ");
        DisplayScreen.setText(Display);
    }
    
    private String RemoveLast(String ActualDisplay)
    {
        if(ActualDisplay.length()>1)
        {
            ActualDisplay = ActualDisplay.substring(0,ActualDisplay.length()-1);
            return ActualDisplay;
        }
        else
        {
            ClearCalculator();
            return "0";
        }
        
    }
    
    private String DeleteUnusedFraction(String s)
    {
        if (s.length()==1)
        {
            return s;
        }
        
        if (".0".equals(s.substring(s.length() - 2))) 
        {
           return RemoveLast(RemoveLast(s));   
        }
         
        
        return s;    
    }
    
    private void PushNumber(String Number)
    {
        String ActualDisplay = DisplayScreen.getText();
        if (!"!".equals(ActualDisplay.substring(ActualDisplay.length() - 1))&& (!"0".equals(ActualDisplay) || ".".equals(Number) ))
        {
            DisplayScreen.setText(ActualDisplay+Number);
        }
        else
        {
            CalculationScreen.setText(" ");
            DisplayScreen.setText(Number);
        }
    }
    
    
    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        calculation='+';
                remembertocalculation2=0;
        remembertocalculation = Double.parseDouble(DisplayScreen.getText());
        String calc = DeleteUnusedFraction(String.valueOf(remembertocalculation)) + " " + calculation + " ";
        ClearCalculator();
        CalculationScreen.setText(calc);
    }//GEN-LAST:event_AddActionPerformed

    private void RemoveLastNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveLastNumberActionPerformed
         String ActualDisplay = DisplayScreen.getText();
         DisplayScreen.setText(RemoveLast(ActualDisplay));
        
    }//GEN-LAST:event_RemoveLastNumberActionPerformed

    private void ResetCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetCalculatorActionPerformed
            ClearCalculator();
    }//GEN-LAST:event_ResetCalculatorActionPerformed

    private void Number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number1ActionPerformed
        PushNumber("1");
    }//GEN-LAST:event_Number1ActionPerformed

    private void Number2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number2ActionPerformed
        PushNumber("2");
    }//GEN-LAST:event_Number2ActionPerformed

    private void Number3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number3ActionPerformed
        PushNumber("3");
    }//GEN-LAST:event_Number3ActionPerformed

    private void Number4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number4ActionPerformed
       PushNumber("4");
    }//GEN-LAST:event_Number4ActionPerformed

    private void Number5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number5ActionPerformed
        PushNumber("5");
    }//GEN-LAST:event_Number5ActionPerformed

    private void Number6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number6ActionPerformed
        PushNumber("6");
    }//GEN-LAST:event_Number6ActionPerformed

    private void Number7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number7ActionPerformed
        PushNumber("7");
    }//GEN-LAST:event_Number7ActionPerformed

    private void Number8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number8ActionPerformed
        PushNumber("8");
    }//GEN-LAST:event_Number8ActionPerformed

    private void Number9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number9ActionPerformed
        PushNumber("9");
    }//GEN-LAST:event_Number9ActionPerformed

    private void Number0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number0ActionPerformed
        PushNumber("0");
    }//GEN-LAST:event_Number0ActionPerformed

    private void NumberdotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberdotActionPerformed
        String ActualDisplay = DisplayScreen.getText();
        if((ActualDisplay.indexOf('.')==-1))
        PushNumber(".");
    }//GEN-LAST:event_NumberdotActionPerformed

    private void SquareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SquareRootActionPerformed
         String ActualDisplay = DisplayScreen.getText();
         if(Double.parseDouble(ActualDisplay)>=0)
         {
             String calcdisplay = "√" + DeleteUnusedFraction(ActualDisplay) + " =" ;
             CalculationScreen.setText(calcdisplay);
             
             DisplayScreen.setText(DeleteUnusedFraction(String.valueOf(Math.sqrt(Double.parseDouble(ActualDisplay)))));
         }
         else
         {
             DisplayScreen.setText("Number lower than 0!");
         }
             
    }//GEN-LAST:event_SquareRootActionPerformed

    private void MultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplyActionPerformed
        calculation='x';
        remembertocalculation2=0;
        remembertocalculation = Double.parseDouble(DisplayScreen.getText());
        String calc = DeleteUnusedFraction(String.valueOf(remembertocalculation)) + " " + calculation + " ";
        ClearCalculator();
        CalculationScreen.setText(calc);
    }//GEN-LAST:event_MultiplyActionPerformed

    private void DivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivideActionPerformed
        calculation='/';
        remembertocalculation2=0;
        remembertocalculation = Double.parseDouble(DisplayScreen.getText());
        String calc = DeleteUnusedFraction(String.valueOf(remembertocalculation)) + " " + calculation + " ";
        ClearCalculator();
        CalculationScreen.setText(calc);
    }//GEN-LAST:event_DivideActionPerformed

    private void XtoPowYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XtoPowYActionPerformed
        calculation='^';
        remembertocalculation2=0;
        remembertocalculation = Double.parseDouble(DisplayScreen.getText());
        String calc = DeleteUnusedFraction(String.valueOf(remembertocalculation)) + " " + calculation + " ";
        ClearCalculator();
        CalculationScreen.setText(calc);
    }//GEN-LAST:event_XtoPowYActionPerformed

    private void SubstractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubstractActionPerformed
        calculation='-';
        remembertocalculation2=0;
        remembertocalculation = Double.parseDouble(DisplayScreen.getText());
        String calc = DeleteUnusedFraction(String.valueOf(remembertocalculation)) + " " + calculation + " ";
        ClearCalculator();
        CalculationScreen.setText(calc);
    }//GEN-LAST:event_SubstractActionPerformed

    private void EqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqualActionPerformed
        if (remembertocalculation2==0) remembertocalculation2= Double.parseDouble(DisplayScreen.getText());
        else remembertocalculation= Double.parseDouble(DisplayScreen.getText());
        String calcdisplay = DeleteUnusedFraction(String.valueOf(remembertocalculation)) + " " + calculation + " " + DeleteUnusedFraction(String.valueOf(remembertocalculation2)) + " =" ;
        CalculationScreen.setText(calcdisplay);
        switch (calculation)
        {
            case '+' ->  DisplayScreen.setText(DeleteUnusedFraction(String.valueOf(remembertocalculation+remembertocalculation2)));
            case '-' ->  DisplayScreen.setText(DeleteUnusedFraction(String.valueOf(remembertocalculation-remembertocalculation2)));
            case 'x' ->  DisplayScreen.setText(DeleteUnusedFraction(String.valueOf(remembertocalculation*remembertocalculation2)));
            case '/' ->  {
                if (remembertocalculation2!=0) DisplayScreen.setText(DeleteUnusedFraction(String.valueOf(remembertocalculation/remembertocalculation2)));
                else DisplayScreen.setText("Cannot divide by 0!");
                
            }
            case '^' -> DisplayScreen.setText(DeleteUnusedFraction(String.valueOf(Math.pow(remembertocalculation,remembertocalculation2))));
        }
    }//GEN-LAST:event_EqualActionPerformed
      
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JLabel CalculationScreen;
    private javax.swing.JLabel DisplayScreen;
    private javax.swing.JButton Divide;
    private javax.swing.JButton Equal;
    private javax.swing.JButton Multiply;
    private javax.swing.JButton Number0;
    private javax.swing.JButton Number1;
    private javax.swing.JButton Number2;
    private javax.swing.JButton Number3;
    private javax.swing.JButton Number4;
    private javax.swing.JButton Number5;
    private javax.swing.JButton Number6;
    private javax.swing.JButton Number7;
    private javax.swing.JButton Number8;
    private javax.swing.JButton Number9;
    private javax.swing.JButton Numberdot;
    private javax.swing.JButton RemoveLastNumber;
    private javax.swing.JButton ResetCalculator;
    private javax.swing.JButton SquareRoot;
    private javax.swing.JButton Substract;
    private javax.swing.JButton XtoPowY;
    // End of variables declaration//GEN-END:variables
}
